<a href="https://colab.research.google.com/github/Byuntil/Deep_learning_project/blob/main/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.1 Numpy: dot, einsum

In [44]:
import numpy as np

A = np.arange(6).reshape(2,3)
print(A,"\n")

#역행렬
R = np.einsum("ij->ji", A)
print(R,"\n")

#dot
Z = np.dot(A,R)
print(Z,"\n")

#einsum
#모든 인덱스 값의 합
S = np.einsum("ij->",A)
print(S,"\n")

#세로 인덱스값의 합(위 아래로 누른다)
P = np.einsum("ij->j",A)
print(P,"\n")

#가로 인덱스값의 합(좌,우로 누른다)
Q = np.einsum("ij->i", A)
print(Q,"\n")

#행렬의 연산
v = np.array([1,2,3])
Y = np.einsum("ij,j->i",A,v)
print(Y,"\n")

#dot과 einsum관계
N = np.einsum("ij,kj->ik",A,A)
print(N,"\n")
print(np.dot(A,R), "\n")

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[ 5 14]
 [14 50]] 

15 

[3 5 7] 

[ 3 12] 

[ 8 26] 

[[ 5 14]
 [14 50]] 

[[ 5 14]
 [14 50]] 



1.2 Numpy: quiz풀이

In [48]:
import numpy as np
#Q.67
a = np.arange(16)
b= a.reshape(2,2,2,2)
print(b)
print("\n=========")
S = b.sum(axis=(-1,-2))
print(S)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]

[[ 6 22]
 [38 54]]


In [54]:
import numpy as np
#Q69
a=np.arange(4).reshape(2,2)
b=np.diag(np.dot(a,a))
c=np.einsum("ij,ji->i",a,a)
print(c)
print(b)

[ 2 11]
[ 2 11]


In [57]:
import numpy as np
#Q72
a = np.arange(4).reshape(2,2)
print(a)
a[[0,1]] = a[[1,0]]
print(a)

[[0 1]
 [2 3]]
[[2 3]
 [0 1]]


In [67]:
import numpy as np
#Q74
d=np.array([1,2,2,3,3,3,4,4,4])
C = np.bincount(d)
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)
print(np.bincount(A))

[0 1 2 3 3]
[1 2 2 3 3 3 4 4 4]
[0 1 2 3 3]


In [72]:
import numpy as np
#Q83
D = np.random.randint(0,20, 20)
print(D)
M = np.bincount(D)
print(M)
print(M.argmax())

[18  8  8 15 11  4  5  1 18  1 11 18 14  8 19 11 17 14  5 15]
[0 2 0 0 1 2 0 0 3 0 0 3 0 0 2 2 0 1 3 1]
8
